import Head from "next/head";
import styles from "@/styles/Home.module.css";
import React, { useState, useEffect } from "react";
import db from "./firebase.js";
import { collection, addDoc } from "firebase/firestore";

export default function Home() {
  var current = new Date();
  const [data, setData] = useState("");
  const [datetime, setDatetime] = useState(new Date);
const [name, setName] = useState("");
const [message, setMessage] = useState("");


const post = async () => {
  const docRef = await addDoc(collection(db, "post"), {
    name:name,
    message:message,
    datetime:datetime
  
  });
  console.log("Document written with ID: ", docRef.id);
  //setData("投稿日時" + current + "名前: " + name + " / メッセージ: " + message);
  //setDate("");
  setName("");
  setMessage("");
};



  return (
    <>
      <Head>
        <title>Next.js Board</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
      <div>
  
  <p>
	名前:
	<br />
	<input
	  type="text"
	  value={name}
	  onChange={(e) => setName(e.target.value)}
	/>
  </p>
  <p>
	内容:
	<br />
	<textarea
	  value={message}
	  onChange={(e) => setMessage(e.target.value)}
	></textarea>
  </p>
  <p>
	<button onClick={post}>投稿</button>
  </p>
</div>
<hr />
<div>{data}</div>
      </main>
    </>
  );
}
